export { Dashboard } from './Dashboard';
export { Login } from './Login';
export { Register } from './Register';
export { Workspaces } from './Workspaces';
export { WorkspaceNew } from './WorkspaceNew';
export { WorkspaceDetail } from './WorkspaceDetail';
export { DocumentEditor } from './DocumentEditor';
export { Documents } from './Documents';
export { Settings } from './Settings';
